---
- name: Check disk usage on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure df command is available
      apt:
        name: coreutils
        state: present

    - name: Check disk usage
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
