---
- name: Check disk usage on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Check disk usage
      raw: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
